### ISSUE TITLE
missing variable in time change prompt

### ISSUE THREAD

**Issue by ndwilliams3** [ringcentral/ringcentral-video-for-hubspot#1]
Was testing this out. If you add a meeting and then change the time, you get an alert prompt...

"Would you like to create a new [missing “en-us.customerDataCommunicator.videoConferencePlugin.integrationName.ringcentral video” translation] meeting with the updated meeting time?"

Looks like there's a missing variable in this callback.

<img width="559" alt="Screen Shot 2020-07-17 at 3 51 18 PM" src="https://user-images.githubusercontent.com/1020854/87829816-628e1a00-c845-11ea-9c79-0bf029518abe.png">

**Comment by zxdong262** [comment]
If the meeting url was `v.ringcentral.com/xxx`, the meeting update is not supported, I guess that is why HubSpot show this message, I think the HubSpot UI has a bug that not showing the right integration name.

**Comment by ndwilliams3** [comment]
It does generate a new meeting ID when you click "Yes" and replaces the link in the meeting body, so the functionality works. However, I'm guessing that the alert message should replace "[missing “en-us.customerDataCommunicator.videoConferencePlugin.integrationName.ringcentral video” translation] with something like "Ringcenral Video" so it reads "Would you like to create a new **Ringcentral Video** meeting with the updated meeting time?"

**Comment by zxdong262** [comment]
@ndwilliams3 I mean it is controlled by HubSpot, not by the integration developer.

**Comment by zxdong262** [comment]
@ndwilliams3 Also it is not published yet, maybe that is the problem.

**Comment by ndwilliams3** [comment]
@zxdong262, That may be it. Thanks for the update. Excited to see this rolling out!

**Comment by zxdong262** [comment]
Now it is in the RingCentral integration, you may try it.
