### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ndwilliams3** [ringcentral/ringcentral-video-for-hubspot#2]
Does this only work with the new Ringcentral video or does it also work with the old Zoom version of  meetings? Most of our team is still using the old Zoom version.

**Comment by zxdong262** [comment]
Both supported

**Comment by ndwilliams3** [comment]
Had someone on my team that's still using the zoom version authorize the app and it looks like there's a problem. see screenshot.
![MicrosoftTeams-image](https://user-images.githubusercontent.com/1020854/88319783-432e3b80-cce2-11ea-9a66-4b3cd192ba88.png)

**Comment by zxdong262** [comment]
@ndwilliams3 Now it is in the RingCentral integration, you may try it
