### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ndwilliams3** [ringcentral/ringcentral-video-for-hubspot#3]
Getting an error when trying to insert the meeting link from the contact record.  
"An error occurred while trying to generate a video conference link."
<img width="768" alt="Screen Shot 2020-07-23 at 10 20 19 AM" src="https://user-images.githubusercontent.com/1020854/88304685-330c6100-ccce-11ea-9855-7a83d03b1abd.png">

**Comment by zxdong262** [comment]
Now it is in the RingCentral integration, you may try it
